#!/usr/bin/env python3
import sys, json
from pprint import pprint
from collections import Counter

def parse_timings(timings_file):
    timings_file = open(timings_file).read().split('\n')[:-1]
    parsed = []
    for line in timings_file:
        line = line[1:-1]
        word, _, timing = line.split(', ')
        start, _ = timing[1:-1].split(':')
        if word not in ['<sil>', '[NOISE]', '[SPEECH]']:
            parsed.append((word, start))
    return parsed

def main():
    args = sys.argv[1:]
    words_file = args[0]
    timings_file = args[1]
    parsed_timings = parse_timings(timings_file)

    word_freqs = Counter(json.load(open(words_file)))
    word_freqs_common = word_freqs.most_common()

    output = []
    for word, freq in word_freqs_common:

        timings_for_word = [int(time) for w, time in parsed_timings if
            w == word]
        output.append(dict(
            word=word, 
            freq=freq,
            positions=timings_for_word))

    print(json.dumps(output, indent=2))

main()
